# Generated by Django 6.0.4 on 2026-04-27 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school')),
            ],
            options={
                'db_table': 'classrooms',
                'ordering': ['name', 'section'],
                'unique_together': {('school', 'name', 'section', 'academic_year')},
            },
        ),
    ]
